### ISSUE TITLE
Lista de aplicabilidad del proyecto

### ISSUE THREAD

**Issue by Edriv** [UTDev-Teamwork/THEO-App#13]
# Entregable 4
## Elaborar el plan de administración del proyecto
> ### Responsable
> **[AP]** José Eduardo Rivas Cuevas [@edriv]

> ### Aprobador
> **[CP]** Francisco Xavier Martínez López [@frankLopz]

> ### Consultor / Informado
> **[IP]** José Ángel Pérez Hernández
---
# [UTD-THEO-04]
## Lista de aplicabilidad del proyecto
> #### Responsable
> Uriel Santillán Paz [@UrielSantillanPaz]

**Comment by Edriv** [comment]
Elaborar carta de aceptación de entregables dirigida a tu aprobador inmediato (Francisco) [@UrielSantillanPaz]

**Comment by UrielSantillanPaz** [comment]
Carta de aprobación de la Lista de aplicabilidad del proyecto realizada @Edriv
