### ISSUE TITLE
Sub Plan de gestión de tiempo

### ISSUE THREAD

**Issue by Edriv** [UTDev-Teamwork/THEO-App#16]
# [UTD-THEO-19]
## Sub Plan de gestión de tiempo
> #### Responsable
> Said Helí García Cuevas [@SaidHGC]

### Este instrumento es parte del instrumento:
_[UTD-THEO-05] Plan de administración de proyectos_

**Comment by SaidHGC** [comment]
Subplan terminado hasta las fechas actuales, en espera de revisión [@Edriv]

**Comment by frankLopz** [comment]
Se aprueba el archivo. @Edriv
