### ISSUE TITLE
Análisis de evaluación financiera

### ISSUE THREAD

**Issue by Edriv** [UTDev-Teamwork/THEO-App#4]
# [UTD-THEO-13]
## Análisis de Evaluación Financiera
> #### Responsable
> Shendel Lopez Almaraz [@Shendel01]

### Este instrumento es parte del instrumento:
_[UTD-THEO-01] Estudio preliminar y Análisis de factibilidad_

**Comment by Edriv** [comment]
Entrega **URGENTE** para revisión @Shendel01.

**Comment by Edriv** [comment]
## Correcciones como revisor del instrumento [UTD-THEO-13]

- [ ] Ajustar pie de documento con su elaborador, revisor y aprobador correspondientes.
- [ ] Arreglar información del instrumento.
- [ ] Ajustar todo el documento a la plantilla corporativa correspondiente.
- [ ] Firmas en el apartado de "Responsables" son únicamente de los miembros de la Comisión del Proyecto.
- [ ] Eliminar comentarios personales del documento.
- [ ] Agregar resumen financiero con totales redondeados a decena de millar.

#### Responsable:
Shendel López Almaraz @Shendel01

**Comment by Shendel01** [comment]
Cambios realizados.

**Comment by Edriv** [comment]
## Correcciones como revisor del instrumento [UTD-THEO-13]

Correcciones anteriores realizadas correctamente
Realiza las correcciones correspondientes a tu carta de aceptación de entregables y notifica a tu aprobador sobre su aprobación.
- [ ] Titulo del documento entregable en la cabecera
- [ ] Participantes involucrados
- [ ] Número de nomenclatura en Nombre del entregable
- [ ] Participantes involucrados en la tabla del pie de página

#### Responsable:
Shendel López Almaraz @Shendel01

**Comment by Shendel01** [comment]
Correcciones hechas.

**Comment by Edriv** [comment]
En espera de aprobación por @frankLopz

**Comment by frankLopz** [comment]
Se aprueba el documento

**Comment by Edriv** [comment]
Enterado, documento bloqueado y entregable cerrado.
